url: https://layer8x.github.io
baseurl: ''

# Site settings
title: Layer8x
email:
description: >
  When we started Layer8x, we had just two things in our possession: a dream and $6 million.
  Today, we have a cloud business the like of which the world has never seen the like of which.
  We hope it doesn't sound arrogant when we say that we are the greatest startup in the world.
  Even though we don't actually exist.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: NightMare
  pic: 1
  position: Tin Foil Hat
  social:
    - title: github
      url: https://github.com/xNightMare

- name: sapslaj
  pic: 2
  position: being sapslaj
  social:
    - title: twitter
      url: https://twitter.com/sapslaj
    - title: github
      url: https://github.com/sapslaj


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/layer8x

# Postal address (add as many lines as necessary)
address:
  - line: 8888 the internet lane
  - line: San Fran, Cali

# Build settings
markdown: kramdown
permalink: pretty
